// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4O4IV9lVAx6YtGvsvpc8W_OrYVuAndwo',
    appId: '1:259110465173:web:d9f3d0c9dab9d001e0b59c',
    messagingSenderId: '259110465173',
    projectId: 'cscaataskmanager',
    authDomain: 'cscaataskmanager.firebaseapp.com',
    storageBucket: 'cscaataskmanager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBzbdE3kX7Gko-XM_W_-Fjtr3Ke2yGQXU',
    appId: '1:259110465173:android:1b0ae1fa0105c60ce0b59c',
    messagingSenderId: '259110465173',
    projectId: 'cscaataskmanager',
    storageBucket: 'cscaataskmanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB58WywHJWCQ2PUo5Z5zSEFKAGWwjz4ZJg',
    appId: '1:259110465173:ios:c08fd04d49666854e0b59c',
    messagingSenderId: '259110465173',
    projectId: 'cscaataskmanager',
    storageBucket: 'cscaataskmanager.firebasestorage.app',
    iosBundleId: 'com.example.cscaaTaskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB58WywHJWCQ2PUo5Z5zSEFKAGWwjz4ZJg',
    appId: '1:259110465173:ios:c08fd04d49666854e0b59c',
    messagingSenderId: '259110465173',
    projectId: 'cscaataskmanager',
    storageBucket: 'cscaataskmanager.firebasestorage.app',
    iosBundleId: 'com.example.cscaaTaskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4O4IV9lVAx6YtGvsvpc8W_OrYVuAndwo',
    appId: '1:259110465173:web:c84d64f039a7b508e0b59c',
    messagingSenderId: '259110465173',
    projectId: 'cscaataskmanager',
    authDomain: 'cscaataskmanager.firebaseapp.com',
    storageBucket: 'cscaataskmanager.firebasestorage.app',
  );
}
